Added sort and filter
IT-Academy-Social-Projects-KRV/Synergy pull request #100
Opened 2021-12-17 22:14 UTC by AntonyJedi

2021-12-18 15:48 UTC, Vadym342 approved these changes

2021-12-18 15:48 UTC, Vadym342 commented on client/src/pages/ProjectListPage/ProjectList.jsx
> +    // sortDirection: ''
Коментарі видалити

2021-12-18 15:48 UTC, Vadym342 commented on client/src/pages/ProjectListPage/ProjectList.jsx
> +    debugger;
Дебагера видалити

2021-12-18 15:48 UTC, Vadym342 commented on client/src/pages/ProjectListPage/components/RangeInput/RangeInput.js
> +      <h3 style={{ paddingLeft: 40 + 'px' }}>Filter by capital</h3>
Стилі бажано виносити в окреме місце щоб не було інлайн стилів

2021-12-18 15:48 UTC, Vadym342 commented on client/src/redux/requests/projectListSortRequest.js
> +  // dispatch(setIsLoader(true));
Це має бути!

2021-12-18 15:48 UTC, Vadym342 commented on client/src/services/projects.service.js
> +  // eslint-disable-next-line max-len
Це перенести на новий рядок, а не виключати еслінт

2021-12-20 10:20 UTC, MattMsh requested changes

2021-12-20 10:20 UTC, MattMsh commented on client/src/services/projects.service.js
> +// eslint-disable-next-line max-len
Як варіант, щоб не писати все в одному рядку, можна зробити форматування, наприклад ось так
```
const getSortProjects = (
    { 
      name, 
      capital, 
      dateStart, 
      dateFinish, 
      sortBy = 'capital', 
      sortDirection = 'ASC' 
    }, 
    page = 1
  ) => {
  return api.get(`/projects?
                    size=10
                    &sortBy=${sortBy}
                    &sortDirection=${sortDirection}
                    &capital=${capital[0]}-${capital[1]}
                    &name=${name}
                    &page=${page}
                    &dateStart=${dateStart}
                    &dateFinish=${dateFinish}
                  `);
```

2021-12-20 10:20 UTC, MattMsh commented on client/src/pages/ProjectListPage/components/SortComponent/SortComponent.js
> +      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingLeft: 40 + 'px', paddingRight: 40 + 'px' }}>
Винось великі стилі в окремий файл

2021-12-21 11:37 UTC, merged